### ISSUE TITLE
Boot output

### ISSUE THREAD

**Issue by mcejp** [ikruusa/mangopi-mq-riscv-images#1]
Hi,
I copied your image to an SD card (`dd if=mangopi-mq-riscv-2023-1-serial-console.img of=/dev/sda bs=1024`), plugged the Mango Pi in, but I am not getting any output on either UART0 (P3 header) or UART1 (P2 header) at 115200 baud.
Where should I be looking? 😅

**Comment by ikruusa** [comment]
Hi! 
Serial console is on UART3. Its not available from P2 or P3 headers but thru special pads near DSI MIPI connector. Look at my picture "Activated interfaces".

**Comment by mcejp** [comment]
Spot on! I soldered a header for the debug output (I'm still puzzled why it is not mounted by default) and now it boots straight into shell.

Thank you.
